### PR TITLE
Fix the default password in the documentation

### PR DESCRIPTION
**Pull request by jeremi**
The default password has changed. This PR fix the doc.

### CODE REVIEW

**Comment by pnabutovsky** [comment]
I'm going to decline this pull request. The default password will change for Primero v1.6.0+. That change should hit Github pretty soon. Sorry about the misleading doc.

**Comment by jeremi** [comment]
@pnabutovsky this change is about the `development` branch where the password has been changed already. It might be confusing for new people like me to the project as the password in the doc of this branch is not the one used in the code.

**Comment by pnabutovsky** [comment]
@jeremi When I said soon, I really meant soon :)   Check the README now. 
The `master` branch, along with `maint_1.6`, now track to v1.6. The `development` branch now represents perspective v1.7 work. Please note that any code in the `development` branch is not guaranteed to be stable.

**Comment by jeremi** [comment]
Sounds good, Thanks!

**Pull request closed without merging**
