### PR TITLE
Caption table

### PR DESCRIPTION
**Pull request by NidhiKJha**
The` <table>` element has an empty `<caption>` element. This pull request is to add Captions in `<table> `

### CODE REVIEW

**Comment by NidhiKJha** [comment]
@IanLawrence @josh-quoin @pnabutovsky Please review my pull request :smile:

**Comment by jtoliver** [comment]
Does this add the caption to html without being visible?

**Comment by NidhiKJha** [comment]
@jtoliver  No, it is visible. I considered making the captions invisible by using the CSS property `display:none`. But I didn't use it further as to make these captions invisible I had to apply this CSS property to` h6 `and I didn't consider hiding `h6` as a good idea. Can you please suggest how can we do it.

**Comment by jtoliver-quoin** [comment]
Lets do this for hiding captions [https://webaim.org/techniques/css/invisiblecontent/#techniques](url)

Under the **Absolutely positioning content off-screen** section

I think you can do something like the following in the overrides const in `app/javascript/config/theme.js`

```
MUIDataTableToolbar: {
  titleText: {
    position: "absolute",
    left: "-10000px"
    top: "auto",
    width: "1px",
    height: "1px",
    overflow: "hidden"
  }
}
```
Looks like just using visibility hidden and text-indent is the old way of doing it.

**Comment by NidhiKJha** [comment]
@jtoliver I added the suggested changes and it's hiding the caption element but not removing the space allocated to this component. 

Screenshot from 2020-06-26 22-34-11

**Comment by jtoliver-quoin** [comment]
@NidhiKJha I think you just need to pull the latest. I think that was recently fixed

**Comment by NidhiKJha** [comment]
@jtoliver I pulled the recent changes and I am on the latest commit. But the accessibility issue is still there.

**Comment by jtoliver-quoin** [comment]
@NidhiKJha If the space is still there check in the browser developer tools that its correctly applying the styles. If position: absolute is correctly place on the correct element it should remove that space.

**Comment by jtoliver-quoin** [comment]
Adding 

```
  titleText: {
    position: "absolute",
    left: "-10000px"
    top: "auto",
    width: "1px",
    height: "1px",
    overflow: "hidden"
  }
```

to the theme the above should work. Could you push what you have with that applied?

**Pull request merged**
